apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-processor-api
  name: location-processor-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5005
    nodePort: 30004
  selector:
    service: location-processor-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-processor-api
  name: location-processor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-processor-api
  template:
    metadata:
      labels:
        service: location-processor-api
    spec:
      containers:
      - image: fthiagomedeiros/location-processor-service-api:latest
        name: location-processor-container
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: config-location-processor-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: config-location-processor-map
              key: KAFKA_TOPIC
      restartPolicy: Always
